name: CI

on:
  push:
    branches:
      - main
      - dev
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}
  schedule:
  - cron:  '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    name: "Node ${{ matrix.node }} - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v4
      with:
        node-version: ${{ matrix.node }}
    - uses: microsoft/playwright-github-action@v1
    - name: install dependencies
      run: npm install
    - name: test
      run: npm test
